version: "3.3"

services:
  database:
    image: postgres
    container_name: database_agendamento
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=agendamento
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
 
      
  app:
    build: .
    container_name: agendamento
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes: 
  pgdata:
    driver: local